name: Notificacion T04E02

on:
  push:
    branches:
      - main

jobs:
  notificar:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar una notificacion a ntfy
        run: |
          curl -X POST "https://ntfy.sh/devops-itla" \
          -H "Title: Nuevo Push en Main JanaricBJ" \
          -H "Priority: urgent" \
          -d "Se hizo un nuevo push al repositorio T04E02"
